### Q1. [Array Creation] Create a 1D NumPy array containing sales values `[12000, 18000, 25000, 15000, 30000, 22000, 40000] Display the array, its data type, number of dimensions, shape, and size.

In [2]:
import numpy as np

In [8]:
sales = np.array([12000, 18000, 25000, 15000, 30000, 22000,40000])

In [9]:
print("Array : ",sales)

Array :  [12000 18000 25000 15000 30000 22000 40000]


In [10]:
print("DataType: ",type(sales))

DataType:  <class 'numpy.ndarray'>


In [13]:
print("Dimension : ",sales.ndim)

Dimension :  1


In [14]:
print("Shape: ",sales.shape)

Shape:  (7,)


In [15]:
print("Size",sales.size)

Size 7


### Q2. [Array Creation] Create an array containing numbers from 10 to 100 with a step size of 10 using NumPy. Reshape it into a 2 × 5 array

In [17]:
arry1 = np.arange(10,101,10)

In [18]:
print(arry1)

[ 10  20  30  40  50  60  70  80  90 100]


In [19]:
arry1 = arry1.reshape(2,5)

In [20]:
print(arry1)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


### 3.[Indexing] From the `sales` array, extract the first value, last value, first four values, and values from index 2 to index 5.

In [27]:
sales

array([12000, 18000, 25000, 15000, 30000, 22000, 40000])

In [28]:
# First value 
sales[0]

np.int64(12000)

In [29]:
# last value
sales[-1]

np.int64(40000)

In [30]:
# First four values
sales[ : 4]

array([12000, 18000, 25000, 15000])

In [31]:
# Values from index 2 to 5
sales[2:6]

array([25000, 15000, 30000, 22000])

### Q4. [2D Indexing] Using the `monthly_sales` 2D array, extract the complete first row, complete second column, and the value located at row index 2 and column index 1.

In [32]:
monthly_sales = np.array([
    [12000, 18000, 25000],
    [15000, 30000, 22000],
    [40000, 28000, 35000]
])

In [33]:
print("First row:", monthly_sales[0, :])

First row: [12000 18000 25000]


In [34]:
print("Second column:", monthly_sales[:, 1])

Second column: [18000 30000 28000]


In [35]:
print("Value at row index 2 and column index 1:", monthly_sales[2, 1])

Value at row index 2 and column index 1: 28000


### Q5. [Boolean Filtering] Find all sales values greater than 25,000 using Boolean indexing

In [40]:
# From sales array
result = sales[sales > 25000]

In [41]:
print(result)

[30000 40000]


### Q6. [Multiple Conditions] Extract sales values that are greater than 15,000 and less than or equal to 35,000

In [43]:
result = sales[(sales > 1500) & (sales <= 35000)]

In [44]:
print(result)

[12000 18000 25000 15000 30000 22000]


### Q7. [Aggregation] Calculate total sales, average sales, minimum sales, maximum sales, median sales, and standard deviation using NumPy.

In [45]:
sales

array([12000, 18000, 25000, 15000, 30000, 22000, 40000])

In [46]:
# Total sales 
sales.sum()

np.int64(162000)

In [47]:
# Average sales 
sales.mean()

np.float64(23142.85714285714)

In [53]:
# Minimum sale
np.min(sales)

np.int64(12000)

In [54]:
# Maximum sale
np.max(sales)

np.int64(40000)

In [55]:
# MEdian sale 
np.median(sales)

np.float64(22000.0)

In [56]:
np.std(sales)

np.float64(8887.04629428331)

### Q8. [Axis Operations] For the `monthly_sales` matrix, calculate total sales for each salesperson (row-wise) and total sales for each month (column-wise).

In [57]:
monthly_sales

array([[12000, 18000, 25000],
       [15000, 30000, 22000],
       [40000, 28000, 35000]])

In [59]:
# Total sales for each salesperson(row wise)
np.sum(monthly_sales,1)

array([ 55000,  67000, 103000])

In [60]:
# Total sales for each month (column wise)
np.sum(monthly_sales,0)

array([67000, 76000, 82000])

### Q9. [Reshaping] Create an array containing numbers 1 to 24 and reshape it into 4 rows and 6 columns. Then convert it back to a 1D array.

In [64]:
array_1d = np.arange(1,25)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [65]:
array_2d = array_1d.reshape(4,6)
array_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [66]:
array_1d = array_2d.reshape(-1)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Q10. [Sorting] Sort the `sales` array in ascending and descending order. Do not modify the original array.

In [67]:
# Sort in ascending order
ascending = np.sort(sales)

In [68]:
ascending

array([12000, 15000, 18000, 22000, 25000, 30000, 40000])

In [69]:
# Sort in descending order
descending = np.sort(sales)[::-1]

In [70]:
descending

array([40000, 30000, 25000, 22000, 18000, 15000, 12000])

In [71]:
# Original sales array 
sales

array([12000, 18000, 25000, 15000, 30000, 22000, 40000])

### Q11. [Unique Values] Using the `customer_ratings` array, find all unique ratings and the number of times each rating occurs.

In [1]:
import numpy as np

customer_ratings = np.array([5, 4, 5, 3, 4, 5, 2, 3, 4, 5])

In [2]:
# Find unique ratings and their counts
ratings, counts = np.unique(customer_ratings, return_counts=True)

In [3]:
ratings

array([2, 3, 4, 5])

In [4]:
counts

array([1, 2, 3, 4])

### Q12. [Missing Values] Using `sales_with_missing`, identify the missing values, count them, and calculate the mean while ignoring missing values.

In [5]:
sales_with_missing = np.array([12000, 18000, np.nan, 15000, 30000, np.nan, 40000])

In [8]:
# Identify missing values
missing_values = np.isnan(sales_with_missing)
missing_values

array([False, False,  True, False, False,  True, False])

In [9]:
# Count missing values
missing_count = np.sum(missing_values)
missing_count

np.int64(2)

In [10]:
# Calculate mean ignoring missing values
mean_sales = np.nanmean(sales_with_missing)
mean_sales

np.float64(23000.0)

### Q13. [Replacing Values] Replace all missing values in `sales_with_missing` with the mean of the available values. Store the cleaned result in a new array.

In [11]:
sales_with_missing = np.array([
    12000, 18000, np.nan, 15000, 30000, np.nan, 40000
])


In [12]:
# Calculate mean ignoring missing values
mean_sales = np.nanmean(sales_with_missing)

In [13]:
# Create a new array and replace missing values
cleaned_sales = np.where(
    np.isnan(sales_with_missing),
    mean_sales,
    sales_with_missing
)

In [14]:
mean_sales

np.float64(23000.0)

In [15]:
cleaned_sales

array([12000., 18000., 23000., 15000., 30000., 23000., 40000.])

### Q14. [Conditional Transformation] Using `np.where()`, create a performance array where sales >= 25,000 are labelled `High` and the remaining values are labelled `Normal`.

In [17]:
sales = np.array([12000, 18000, 25000, 15000, 30000, 22000, 40000])

In [18]:
# Create performance array
performance = np.where(sales >= 25000, "High", "Normal")

In [19]:
sales

array([12000, 18000, 25000, 15000, 30000, 22000, 40000])

In [20]:
performance

array(['Normal', 'Normal', 'High', 'Normal', 'High', 'Normal', 'High'],
      dtype='<U6')

### 15. [Vectorized Calculation] A company gives a 10% incentive on each sales value. Calculate the incentive and final sales-plusincentive for every transaction without using a Python loop.

In [21]:
sales = np.array([12000, 18000, 25000, 15000, 30000, 22000, 40000])

In [22]:
# Calculate 10% incentive
incentive = sales * 0.10

In [23]:
# Calculate final sales + incentive
final_sales = sales + incentive

In [24]:
incentive

array([1200., 1800., 2500., 1500., 3000., 2200., 4000.])

In [25]:
final_sales

array([13200., 19800., 27500., 16500., 33000., 24200., 44000.])

### Q16. [Broadcasting] Given quarterly sales for 4 employees and a common bonus of 5,000, use NumPy broadcasting to add the bonus to every employee's sales.

In [26]:
quarterly_sales = np.array([50000, 65000, 45000, 70000])

In [27]:
bonus = 5000

In [28]:
final_sales = quarterly_sales + bonus

In [29]:
final_sales

array([55000, 70000, 50000, 75000])

###  Q17. [Array Combination] Combine `q1_sales` and `q2_sales` first vertically and then horizontally. Display the shapes of both resulting arrays.

In [30]:
q1_sales = np.array([10000, 15000, 20000])
q2_sales = np.array([12000, 18000, 22000])

In [33]:
# Vertical combination
vertical = np.vstack((q1_sales, q2_sales))
vertical

array([[10000, 15000, 20000],
       [12000, 18000, 22000]])

In [34]:
# Horizontal combination
horizontal = np.hstack((q1_sales, q2_sales))
horizontal

array([10000, 15000, 20000, 12000, 18000, 22000])

In [35]:
print("Shape:", vertical.shape)

Shape: (2, 3)


In [36]:
print("Shape:", horizontal.shape)

Shape: (6,)


### Q18. [Statistical Analysis] Using `employee_scores`, calculate each employee's average score and identify the employee index having the highest average score.

In [37]:
employee_scores = np.array([
    [80, 75, 90],
    [65, 70, 60],
    [90, 85, 95],
    [70, 80, 75]
])

In [38]:
# Calculate average score of each employee
avg_score = np.mean(employee_scores,axis = 1)

In [39]:
# Find the index of employee with highest average
high_index = np.argmax(avg_score)

In [40]:
avg_score

array([81.66666667, 65.        , 90.        , 75.        ])

In [42]:
high_index

np.int64(2)

### Q19. [Correlation] Calculate the correlation coefficient between `advertising_spend` and `revenue`. Based only on the coefficient, state whether the relationship is positive or negative and whether it appears weak or strong.

In [43]:
advertising_spend = np.array([10000, 20000, 30000, 40000, 50000])
revenue = np.array([50000, 70000, 90000, 110000, 130000])

In [44]:
# Calculate correlation coefficient
correlation = np.corrcoef(advertising_spend, revenue)[0, 1]

In [45]:
print("Correlation coefficient:", correlation)

Correlation coefficient: 1.0


In [46]:
if correlation > 0:
    print("Relationship: Positive")
else:
    print("Relationship: Negative")

Relationship: Positive


In [47]:
if abs(correlation) >= 0.7:
    print("Strength: Strong")
else:
    print("Strength: Weak")

Strength: Strong


### Q20. [Interview Challenge] Using the `sales` array, calculate the percentage contribution of every transaction to total sales, identify the transaction with the highest contribution, and return only transactions whose contribution is above the average contribution

In [54]:
sales = np.array([12000, 18000, 25000, 15000, 30000, 22000, 40000])

In [55]:
# 1. Calculate total sales
total_sales = np.sum(sales)
total_sales

np.int64(162000)

In [56]:
# 2. Calculate percentage contribution of each transaction
contribution = (sales / total_sales) * 100
contribution

array([ 7.40740741, 11.11111111, 15.43209877,  9.25925926, 18.51851852,
       13.58024691, 24.69135802])

In [61]:
# 3. Find transaction with highest contribution
highest_index = np.argmax(contribution)
highest_transaction = sales[highest_index]
highest_index

np.int64(6)

In [62]:
highest_transaction

np.int64(40000)

In [63]:
# 4. Calculate average contribution
average_contribution = np.mean(contribution)
average_contribution

np.float64(14.285714285714286)

In [64]:
# 5. Select transactions above average contribution
above_average = sales[contribution > average_contribution]
above_average

array([25000, 30000, 40000])